name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§¾ Checkout code
        uses: actions/checkout@v3

      - name: ðŸ” Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: ðŸ“¦ Copy files to VPS
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.DEPLOY_DIR }}

      - name: Upload API .env to server
        run: |
          echo "${{ secrets.DEV_ENV_FILE_API }}" | ssh -i ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cat > /var/www/acc_bot/src/app/.dev.env"

      - name: Upload BOT .env to server
        run: |
          echo "${{ secrets.DEV_ENV_FILE_BOT }}" | ssh -i ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cat > /var/www/acc_bot/src/tg_bot/.dev.env"

      - name: ðŸš€ Deploy with docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e  # ÐŸÑ€ÐµÑ€Ñ‹Ð²Ð°Ñ‚ÑŒ Ð²Ñ‹Ð¿Ð¾Ð»Ð½ÐµÐ½Ð¸Ðµ Ð¿Ñ€Ð¸ Ð¾ÑˆÐ¸Ð±ÐºÐµ
          
            cd ${{ secrets.DEPLOY_DIR }}
          
            echo "ðŸ“¦ Stopping and removing old containers"
            docker-compose down --remove-orphans
          
            echo "ðŸ§¹ Removing old images"
            docker image prune -af
          
            echo "ðŸ”§ Building new containers"
            docker-compose build
          
            echo "ðŸš€ Starting services"
            docker-compose up -d
          
            echo "ðŸ“ Running Alembic migrations"
            # Ð—Ð°Ð¼ÐµÐ½Ð¸Ñ‚Ðµ fastapi_app Ð½Ð° Ð¸Ð¼Ñ ÐºÐ¾Ð½Ñ‚ÐµÐ¹Ð½ÐµÑ€Ð° Ð¸Ð· docker-compose (service name)
            docker-compose exec -T "fastapi-app" uv run alembic upgrade head
          EOF
