name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: üßæ Checkout code
        uses: actions/checkout@v3

      - name: üîê Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: üì¶ Copy files to VPS
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.DEPLOY_DIR }}

      - name: Generate api .env file
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cat <<EOT > ${{ secrets.DEPLOY_DIR }}/src/app/.env
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=postgres
          POSTGRES_DB=akk_bot
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=5432
          DEBUG=${{ secrets.DEBUG }}
          EOT
          EOF

      - name: Generate tg_bot .env file on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cat <<EOT > ${{ secrets.DEPLOY_DIR }}/src/tg_bot/.env
          KAFKA_BOOTSTRAP_SERVERS=localhost
          KAFKA_PORT=29092
          KAFKA_TOPIC=analytics-events
          KAFKA_CONSUMER_GROUP=analytics-consumer-group
          
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          DEBUG=${{ secrets.DEBUG }}
          EOT
          EOF



      - name: üöÄ Deploy with docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e  # –ü—Ä–µ—Ä—ã–≤–∞—Ç—å –≤—ã–ø–æ–ª–Ω–µ–Ω–∏–µ –ø—Ä–∏ –æ—à–∏–±–∫–µ
          
            cd ${{ secrets.DEPLOY_DIR }}
          
            echo "üì¶ Stopping and removing old containers"
            docker-compose down --remove-orphans
          
            echo "üßπ Removing old images"
            docker image prune -af
          
            echo "üîß Building new containers"
            docker-compose build
          
            echo "üöÄ Starting services"
            docker-compose up -d
          
            echo "üìÅ Running Alembic migrations"
            # –ó–∞–º–µ–Ω–∏—Ç–µ fastapi_app –Ω–∞ –∏–º—è –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞ –∏–∑ docker-compose (service name)
            docker-compose exec -T "fastapi-app" uv run alembic upgrade head
          EOF
